/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.objectsandbinaryfiles.ui;

import static com.objectsandbinaryfiles.files.DataAndList.persons;
import com.objectsandbinaryfiles.files.SaveFile;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MIDP9
 */
public class TableOfPersons extends javax.swing.JInternalFrame {

    /**
     * Creates new form TableOfPersons
     */
    public TableOfPersons() {
        initComponents();
        actualizeTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        puTable = new javax.swing.JPopupMenu();
        miDeleteUser = new javax.swing.JMenuItem();
        editPerson = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        puTable.setToolTipText("Borrar Usuario");
        puTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                puTableMouseClicked(evt);
            }
        });

        miDeleteUser.setText("Borrar Persona");
        miDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDeleteUserActionPerformed(evt);
            }
        });
        puTable.add(miDeleteUser);

        editPerson.setText("Editar persona");
        puTable.add(editPerson);

        setClosable(true);
        setTitle("Tabla de usuarios");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DPI", "Nombre", "Edad"
            }
        ));
        jTable1.setComponentPopupMenu(puTable);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void puTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_puTableMouseClicked
        persons.remove(jTable1.getSelectedRow());
    }//GEN-LAST:event_puTableMouseClicked

    private void miDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDeleteUserActionPerformed
        if ( jTable1.getSelectedRow() > -1 ) {
            JOptionPane.showMessageDialog(rootPane, "Ha eliminado a: " + persons.get(jTable1.getSelectedRow()).getName());
            persons.remove(jTable1.getSelectedRow());
            SaveFile.saveObjects();
            this.actualizeTable();
        }
    }//GEN-LAST:event_miDeleteUserActionPerformed

    public void actualizeTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for ( int i = 0 ; i < persons.size() ; i++ ){
            model.addRow(persons.get(i).getInfoAsObjectArray());
        }
        jTable1.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem editPerson;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem miDeleteUser;
    private javax.swing.JPopupMenu puTable;
    // End of variables declaration//GEN-END:variables
}
